# Generated by Django 5.1.3 on 2024-11-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_deck_deckcard_deck_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='user',
        ),
    ]
